package sk.intersoft.vicinity.platform.semantic.lifting.model;

public class ThingJSON {
    public static final String idAnnotation = "@id";
    public static final String typeAnnotation = "@type";

    public static final String type = "type";
    public static final String oid = "oid"; // VICINITY ID generated by NGHBR
    public static final String name = "name";
    public static final String properties = "properties";
    public static final String actions = "actions";
    public static final String events = "events";


    // ID mapping in results
    public static final String result = "result";
    public static final String mapping = "mapping";
    public static final String lifting = "lifting";
    public static final String infrastructureId = "infrastructure-id";

    // property/action

    public static final String output = "output";
    public static final String input = "input";

    // links
    public static final String readLink = "read_link";
    public static final String writeLink = "write_link";
    public static final String href = "href";

    // property/action input/output
    public static final String units = "units";
    public static final String datatype = "datatype";

    // property
    public static final String pid = "pid";
    public static final String monitors = "monitors";
    public static final String observes = "observes";

    // action
    public static final String aid = "aid";
    public static final String affects = "affects";
    public static final String forProperty = "forProperty";

    // event
    public static final String eid = "eid";

    // original json source
    public static final String jsonSource = "jsonSource";

}
